name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 18 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate GitHub Profile 3D Contribution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate 3D Contribution
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
